# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6254a3a648f6621a18582e1a588f06d967b86d3051ae57d4b5ebd56d2fc76b44d2dca0e210119ab2bb19039f13e10ae28ac34d061898fe85d5e33dcb0d13f212

test:
  secret_key_base: 41441bbbb85f83f646f2eff926bdd0cad453a63be20ceb788620a1748daaf5eb4547c081431f3745f9bd512dec958c564925a94a6f3ee114f4fcc90ca6c2b667

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
